apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-hard
spec:
  selector:
    matchLabels:
      app: nginx-hard
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-hard
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx-hard
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx-hard
        image: nginx:1.15
        ports:
        - containerPort: 80
