apiVersion: v1
kind: Service
metadata:
  name: my-service-with-no-selector
spec:
  # cluster IP is defined => not a headless service even if no selector is present
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  # same name as service => required for matching
  name: my-service-with-no-selector
subsets:
  - addresses:
      - ip: 160.153.133.176
    ports:
      - port: 80