apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: job-completions-parallelism
spec:
  completions: 8
  # For a non-parallel job, do not set the parallelism field.
  parallelism: 5
  template:
    metadata:
      name: job-completions-parallelism
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit
      restartPolicy: Never