apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: job-completions
spec:
  completions: 8
  template:
    metadata:
      name: job-completions
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl"]
          args: ["-Mbignum=bpi", "-wle", "print bpi(2000)"]
      # Do not restart containers after they exit
      restartPolicy: Never