apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  rules:
  - host: my-super-site.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80