apiVersion: v1
kind: Pod
metadata:
  name: pod-envs
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - configMapRef:
        name: my-config
    - secretRef:
        name: my-secret
  restartPolicy: Never