apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-soft
spec:
  selector:
    matchLabels:
      app: nginx-soft
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-soft
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx-soft
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx-soft
        image: nginx:1.15
        ports:
        - containerPort: 80
