apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    app: {{ .Chart.Name | quote }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Chart.Name | quote }}

