apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-host-path
spec:
  containers:
    - image: nginx:1.15
      name: test-container
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /tmp
        # this field is optional
        type: Directory